name: Build
on:
  push:

env:
  NINJA_STATUS: '[%f/%t %e %r]'

jobs:
  MSVC:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, amd64_x86]
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
    - name: Build
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build .
        ls
    - name: Test
      if: ${{ matrix.arch == 'x64' }} # 64bit java.exe is selected for 32bit target
      run: |
        ctest -V

  AppleClang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dev tools
      run: |
        brew install openjdk
        brew info openjdk
    - name: Build
      #env:
      #  JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      run: |
        export JAVA_HOME=/usr/local/opt/openjdk
        cmake  -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build .
    - name: Test
      #env:
      #  JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      run: |
        ls -l lib* *.jar
        export JAVA_HOME=/usr/local/opt/openjdk
        ctest -V

  GCC:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc_ver: [9, 10]
        std: [14, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Install dev tools
      run: sudo apt install openjdk-11-jdk-headless
    - name: Build
      run: |
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.std }} -DCMAKE_C_COMPILER=gcc-${{ matrix.cc_ver }} -DCMAKE_CXX_COMPILER=g++-${{ matrix.cc_ver }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build .
    - name: Test
      run: |
        ls -l lib* *.jar
        ctest -V

  Clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc_ver: [10, 11, 12]
        std: [14, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Install dev tools
      run: sudo apt install openjdk-11-jdk-headless
    - name: Build
      run: |
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.std }} -DCMAKE_C_COMPILER=clang-${{ matrix.cc_ver }} -DCMAKE_CXX_COMPILER=clang++-${{ matrix.cc_ver }}  -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build .
        ls -l lib* *.jar
    - name: Test
      run: ctest -V
