name: Build
on:
  push:

# JAVA_HOME_13_X64 for win, JAVA_HOME_11_X64 otherwise

jobs:
  MSVC:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build
      run: |
        cmake  -DCMAKE_BUILD_TYPE=Release .
        cmake --build .
    - name: Test
      run: |
        ctest

  AppleClang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dev tools
      run: |
        brew install openjdk
        brew info openjdk
    - name: Build
      #env:
      #  JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      run: |
        export JAVA_HOME=/usr/local/opt/openjdk
        cmake  -DCMAKE_BUILD_TYPE=Release .
        cmake --build .
        ls -l lib* *.jar
    - name: Test
      #env:
      #  JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      run: |
        export JAVA_HOME=/usr/local/opt/openjdk
        ctest

  GCC:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        cc_ver: [9, 10, 11]
        std: [14, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Install dev tools
      run: |
        brew install openjdk
        brew info openjdk
    - name: Build
      run: |
        export JAVA_HOME=/usr/local/opt/openjdk
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.std }} -DCMAKE_C_COMPILER=gcc-${{ matrix.cc_ver }} -DCMAKE_CXX_COMPILER=g++-${{ matrix.cc_ver }} -DCMAKE_BUILD_TYPE=Release .
        cmake --build .
        ls -l lib* *.jar
    - name: Test
      run: |
        export JAVA_HOME=/usr/local/opt/openjdk
        ctest

  Clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc_ver: [10, 11, 12]
        std: [14, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Install dev tools
      run: sudo apt install openjdk-11-jdk-headless
    - name: Build
      run: |
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.std }} -DCMAKE_C_COMPILER=clang-${{ matrix.cc_ver }} -DCMAKE_CXX_COMPILER=clang++-${{ matrix.cc_ver }}  -DCMAKE_BUILD_TYPE=Release .
        cmake --build .
        ls -l lib* *.jar
    - name: Test
      run: ctest
